export const CHANGE_CLICK_STATE = 'clickState/CHANGE_CLICK_STATE';
export const CHANGE_TV_CLICK_STATE = 'clickState/CHANGE_TV_CLICK_STATE';
export const CHANGE_FALSE_CLICK_STATE = 'clickState/CHANGE_FALSE_CLICK_STATE';
export const CHANGE_FALSE_TV_CLICK_STATE = 'clickState/CHANGE_FALSE_TV_CLICK_STATE';